### PR TITLE
ENH: Store size of full dataset in SQL database

### PR DESCRIPTION
**Pull request by pastewka**
This PR enables storing and retrieving of the size of the dataset.

### CODE REVIEW

**Comment by tjelvar-olsson** [comment]
Hi Lars,

I've had a quick look at this. It looks good. I might need to  update the README to reflect the change in the behaviour (specifically, https://github.com/jic-dtool/dtool-lookup-server#listing-all-datasets).

Also, it would be interesting for me to find out how you will benefit from this change?

I'll try to merge this change and make a new release at some point over the next couple of weeks. Does that time scale work with you?

Best,
Tjelvar

**Comment by tjelvar-olsson** [comment]
A couple of more thoughts:

1. It may be worth adding the total number of items in the dataset as well
2. It may also be worth including these "dataset summary statistics" to the mongo dataset document as well

**Comment by pastewka** [comment]
Hi @tjelvar-olsson - thanks for looking at this and your suggestions sound good. Let me implement those here. There is no rush merging this.

**Comment by pastewka** [comment]
Hi @tjelvar-olsson:

1. I've added the number of total items to the database
2. The Mongo dataset also includes this information (it already did before as it's simply storing the admin metadata dictionary)
3. I've added a Docker environment for developing the lookup server - please have a look and see if you want this in there, happy to remove it again

**Comment by pastewka** [comment]
Another comment: For some reason that I do not understand I had to manually register the cli here: https://github.com/pastewka/dtool-lookup-server/blob/b7f328d064f9aff525b1c736e7042c851c16bf8d/dtool_lookup_server/__init__.py#L82

Happy to reverse this. Not sure what's going on.

**Comment by tjelvar-olsson** [comment]
> Another comment: For some reason that I do not understand I had to manually register the cli here: https://github.com/pastewka/dtool-lookup-server/blob/b7f328d064f9aff525b1c736e7042c851c16bf8d/dtool_lookup_server/__init__.py#L82
> 
> Happy to reverse this. Not sure what's going on.

I don't understand why you would need to do that either. What happened before you registered them there?

**Comment by pastewka** [comment]
The command were simply not available from the `flask` command line tool. How is `cli` imported normally?

**Comment by tjelvar-olsson** [comment]
Overall it looks good. I'll try test out the docker files to get a feel if they should be included or not.

Thinking of merging this into a branch called version-1 or something similar.

**Comment by pastewka** [comment]
You mean as opposed to `version-2` which would have the redesigned API?

**Comment by tjelvar-olsson** [comment]
> The command were simply not available from the `flask` command line tool. How is `cli` imported normally?

I believe they are registered here: https://github.com/jic-dtool/dtool-lookup-server/blob/12baba73eebc668b4998ae2c2ea43946dc3bf856/setup.py#L18-L21

Are you missing a `pip install dtool-lookup-server` or a `python setup.py install` or a `python setup.py develop` command?

**Comment by tjelvar-olsson** [comment]
> You mean as opposed to `version-2` which would have the redesigned API?

I was thinking that `version-1` would have the redesigned API and this change (we are not v1 yet, only 0.17.2). But happy to call it v2 if it makes it clearer.

**Comment by pastewka** [comment]
No that's perfect. v1 it is. Will try playing with this flask-smorest thing this week...

**Comment by pastewka** [comment]
You were of course right @tjelvar-olsson - there was a `pip install -e .` (or similar) missing.

FYI, I use the docker-compose `devel.yml` within PyCharm for development but you can of course also run it outside of PyCharm.

**Comment by tjelvar-olsson** [comment]
@pastewka I've looked at the code and the docker setup it all looks good.

1. Can we move devel.yml into the docker subdirectory to make the top level directory less cluttered?
2. [Optional] Could you add a README to the ./docker directory to explain the setup and usage of your docker-compose system?

**Comment by pastewka** [comment]
Hi @tjelvar-olsson , I've moved the YAML file and added a README

**Comment by tjelvar-olsson** [comment]
@pastewka thank you, it is merged now :)

**Comment by pastewka** [comment]
Perfect, thanks!

**Pull request merged**
