### PR TITLE
WIP - OpenAPI support

### PR DESCRIPTION
**Pull request by ljyanesm**
After starting the server, navigate to /doc/swagger to view the API

**Note**: There's a question regarding how plugins are going to be integrated, currently they require the use of `flask-smorest` blueprints, but maybe this should be optional?

### CODE REVIEW

**Comment by pastewka** [comment]
I don't see an issue requiring flask-smorest for plugins. (Is this what you are saying @ljyanesm?)

**Comment by ljyanesm** [comment]
Dear @pastewka 

As an example:
https://github.com/jic-dtool/dtool-lookup-server-annotation-filter-plugin/blob/70ef2a5f64db65a767a238c9da01f50a674aea7d/dtool_lookup_server_annotation_filter_plugin/__init__.py#L2

Would have to use:
https://flask-smorest.readthedocs.io/en/latest/api_reference.html#flask_smorest.Blueprint

I am ambivalent because it is only due to the openapi definition that Blueprints should come from flask_smorest and the corrective action when one uses flask.Blueprint might not be immediately clear. Also, plugins such as the linked above would need to be updated. Not sure if @tjelvar-olsson has an opinion about the matter?

**Comment by jotelha** [comment]
The decorator `@bp.response(200, Dict)` (https://github.com/ljyanesm/dtool-lookup-server/blob/54261cc356722aea7bada65d35a1824be0d47594/dtool_lookup_server/dataset_routes.py#L209) leads to the error 

```Resolver error at paths./dataset/annotations.post.responses.200.content.application/json.schema.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/<fields.Dict(dump_default=<marshmallow.missing>, attribute=None, validate=None, required=False, load_only=False, dump_only=False, load_default=<marshmallow.missing>, allow_none=False, error_messages={'required': 'Missing data for required field.', 'null': 'Field may not be null.', 'validator_failed': 'Invalid value.', 'invalid': 'Not a valid mapping type.'})> does not exist in document
``` 

on the `/doc/swagger` route.

**Comment by tjelvar-olsson** [comment]
@ljyanesm thank you! This is awesome. I'll merge now.

**Pull request merged**
