### PR TITLE
Implementing a modular config

### PR DESCRIPTION
**Pull request by jotelha**
This first commit is what we used to do for plugin configs, extended to the entry point groups `extensions`, `search`, and `retrieve`. So far, we never constructed a merged flask config. Think about how to have extensions build their own configurations and have them enter the app-central flask config https://flask.palletsprojects.com/en/2.2.x/api/#configuration

### CODE REVIEW

**Comment by jotelha** [comment]
@tjelvar-olsson this is one possibility for having plugin configuration parameters collected within the global Flask app config without prescribing any particular structure like https://github.com/jic-dtool/dtool-lookup-server/blob/d7c5fc1c26c5641e00c346f89c086adce46e3d44/dtool_lookup_server/config.py#L17-L79, apart from implementing the `get_config()` on the plugin class. Also tried to outline what plugins must, should and may do in the ABC docstrings. Please have a look and let me know what you think.

**Comment by tjelvar-olsson** [comment]
Hi Johannes,

It looks good. I have three main comments:

1. You need to decorate the `def get_config` method with `@abstractmethod` (like `def register_dataset`). This will ensure that whoever inherits the ExtensionABC class will have to implement the method.
2. It is not clear to me why you are forcing all the keys of the config to be lowercase. Is this to make it pretty to display or is there some other reason. I would argue that it might be better to leave the keys to be in upper case so that it is easier for admins to understand what the name of the environment variable they have to export is to override the setting.
3. I'm not sure it is good practise to expose the details of databases in the config route, e.g. the database name/collection etc, this might make it easier for hackers to break the system.

**Comment by jotelha** [comment]
Hi @tjelvar-olsson , thanks for the comments, hope you had a good start in 2023. 

1. I removed the requirement of implementing the `get_config()` method deliberately in the latest commit https://github.com/jic-dtool/dtool-lookup-server/pull/41/commits/4d1ca70927fa2a9aeb3456ab2b094d5c056b57a6, since a plugin does not necessarily have to have custom a configuration and hence no need to provide these. If you think it's better practice to always enforce implementing the `get_config` method, even if there is nothing to be returned, then I'll stick the `@abstractmethod` back in.
2. The conversion to lowercase had been in the master at https://github.com/jic-dtool/dtool-lookup-server/blob/d7c5fc1c26c5641e00c346f89c086adce46e3d44/dtool_lookup_server/config.py#L66-L79 since ~ 2 years, and, yes, initially I put it that way just because it integrates better into the largely lower case keys of response JSON. Currently, a typical response of the `/config/info/` route would look like this, 
    ```json
    {
      "api_spec_options": {
        "components": {
          "headers": {
            "PAGINATION": {
              "description": "Pagination metadata",
              "schema": {
                "$ref": "#/components/schemas/PaginationMetadata"
              }
            }
          },
          "responses": {
            "DEFAULT_ERROR": {
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Error"
                  }
                }
              },
              "description": "Default error response"
            },
            "UNPROCESSABLE_ENTITY": {
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Error"
                  }
                }
              },
              "description": "Unprocessable Entity"
            }
          },
          "schemas": {
            "BaseURI": {
              "properties": {
                "base_uri": {
                  "maxLength": 255,
                  "nullable": true,
                  "type": "string"
                }
              },
              "type": "object"
            },
            ...
            "User": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "is_admin": {
                  "type": "boolean"
                },
                "username": {
                  "maxLength": 64,
                  "nullable": true,
                  "type": "string"
                }
              },
              "type": "object"
            },
            ...
          },
          "securitySchemes": {
            "bearerAuth": {
              "bearerFormat": "JWT",
              "scheme": "bearer",
              "type": "http"
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "servers": [
          {
            "description": "dtool-lookup-server demo instance",
            "url": "https://demo.dtool.dev/lookup"
          }
        ],
        "x-internal-id": "2"
      },
      "api_title": "dtool-lookup-server API",
      "api_version": "v1",
      "cors_expose_headers": [
        "X-Pagination"
      ],
      "dtool_lookup_server_dependency_graph_plugin": "cannot import name 'ConfigSchema' from 'dtool_lookup_server.schemas' (/src/dtool-lookup-server/dtool_lookup_server/schemas.py)",
      "dtool_lookup_server_direct_mongo_plugin": "cannot import name 'ConfigSchema' from 'dtool_lookup_server.schemas' (/src/dtool-lookup-server/dtool_lookup_server/schemas.py)",
      "dtool_lookup_server_notification_plugin": "cannot import name 'mongo' from 'dtool_lookup_server' (/src/dtool-lookup-server/dtool_lookup_server/__init__.py)",
      "dtool_lookup_server_plugin_scaffolding": "cannot import name 'ConfigSchema' from 'dtool_lookup_server.schemas' (/src/dtool-lookup-server/dtool_lookup_server/schemas.py)",
      "jsonify_prettyprint_regular": true,
      "jwt_algorithm": "RS256",
      "jwt_header_name": "Authorization",
      "jwt_header_type": "Bearer",
      ...
      "jwt_token_location": "headers",
      "openapi_redoc_path": "/redoc",
      "openapi_redoc_url": "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js",
      "openapi_swagger_ui_path": "/swagger",
      "openapi_swagger_ui_url": "https://cdn.jsdelivr.net/npm/swagger-ui-dist/",
      "openapi_url_prefix": "/doc",
      "openapi_version": "3.0.2",
      "retrieve_mongo_collection": "datasets",
      "retrieve_mongo_db": "dtool_info",
      "retrieve_mongo_uri": "mongodb://mongodb:27017/",
      "search_mongo_collection": "datasets",
      "search_mongo_db": "dtool_info",
      "search_mongo_uri": "mongodb://mongodb:27017/",
      "sqlalchemy_track_modifications": false,
      "version": "0.17.2"
    }
    ```
    and I'd prefer to keep it that way for now as we'll likely hit a few foreseeable issues on our client side if we switch to upper case now. But I can open an issue and pursue this in another branch with somewhat lower priority.
3. Will add those to the exclusions.

Best,

Johannes

**Comment by jotelha** [comment]
A follow up for 2.: What I will do for now is removing the conversion to lowercase from the plugin methods, e.g. from https://github.com/jotelha/dtool-lookup-server-retrieve-plugin-mongo/blob/38f09f353fce847c5e3ddee81b2b093d7054158d/dtool_lookup_server_retrieve_plugin_mongo/config.py#L7-L23 and so on, and apply it only just ahead of responding to the `/config/info` route, i.e. in https://github.com/jotelha/dtool-lookup-server/blob/4d1ca70927fa2a9aeb3456ab2b094d5c056b57a6/dtool_lookup_server/config_routes.py#L22-L32 . Ok?

**Comment by jotelha** [comment]
Now I remember the true reason for making `get_config` not abstract. If it's abstract, the tests won't run through with the current dependencies, e.g.
```
______________________ ERROR collecting tests/test_cli.py ______________________
tests/test_cli.py:4: in <module>
    import dtool_lookup_server
dtool_lookup_server/__init__.py:196: in <module>
    search = search_entrypoints[0]()
E   TypeError: Can't instantiate abstract class MongoSearch with abstract methods get_config
_________________ ERROR collecting tests/test_config_routes.py _________________
tests/test_config_routes.py:4: in <module>
    import dtool_lookup_server
dtool_lookup_server/__init__.py:196: in <module>
    search = search_entrypoints[0]()
E   TypeError: Can't instantiate abstract class MongoSearch with abstract methods get_config
```
in CI until the according changes in these plugins are merged into master as well.

**Comment by jotelha** [comment]
> Hi @jotelha ,
> 
> It looks good. I have three main comments:
> 
>     1. You need to decorate the `def get_config` method with `@abstractmethod` (like `def register_dataset`). This will ensure that whoever inherits the ExtensionABC class will have to implement the method.
> 
>     2. It is not clear to me why you are forcing all the keys of the config to be lowercase. Is this to make it pretty to display or is there some other reason. I would argue that it might be better to leave the keys to be in upper case so that it is easier for admins to understand what the name of the environment variable they have to export is to override the setting.
> 
>     3. I'm not sure it is good practise to expose the details of databases in the config route, e.g. the database name/collection etc, this might make it easier for hackers to break the system.

Hi @tjelvar-olsson, I think I explained why I would keep points 1 and 2 in the above  as they are and addressed 3, can we merge this?

**Comment by jotelha** [comment]
Subsumed in https://github.com/jic-dtool/dtool-lookup-server/pull/47

**Pull request closed without merging**
